# Generated by Django 4.2.14 on 2024-07-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('ingredients', models.CharField(help_text='Enter the ingredients separated by commas', max_length=255)),
                ('cooking_time', models.FloatField(help_text='Enter the cooking time in minutes')),
                ('difficulty', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
